
default: &default
  adapter: pg
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: pg
  database: db/development.pg


test:
  adapter: pg
  database: db/test.pg

production:
  adapter: pg
  database: db/production.pg
